name: Run PHPUnit tests

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  tests:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        php: [7.3, 7.4, 8.0, 8.1, '8.2']
        laravel: ['8.*', '11.*']
        dependency: [prefer-lowest, prefer-stable]
        include:
          - laravel: 8.*
            testbench: ^6.23
          - laravel: 11.*
            testbench: ^9.0
        exclude:
          - laravel: 11.*
            php: 7.3
          - laravel: 11.*
            php: 7.4
          - laravel: 11.*
            php: 8.0
          - laravel: 11.*
            php: 8.1

    name: P${{ matrix.php }} - L${{ matrix.laravel }} - ${{ matrix.dependency }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: ~/.composer/cache/files
          key: dependencies-laravel-${{ matrix.laravel }}-php-${{ matrix.php }}-composer-${{ hashFiles('composer.json') }}

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: dom, curl, libxml, mbstring, pcntl, intl, exif, iconv
          coverage: none

      - name: Install dependencies
        run: |
          composer require "illuminate/support:${{ matrix.laravel }}" "orchestra/testbench:${{ matrix.testbench }}" --no-interaction --no-update --no-progress
          composer update --${{ matrix.dependency }} --prefer-dist --no-interaction --no-suggest --no-progress

      - name: Execute tests
        run: vendor/bin/phpunit
